// lets pray to save correctly

var phrases = new Array(
    "Welcome to my humble abode..",
    "I wonder how much computing power is wasted by having this JS?",
    "Hideo Kojima would scan you.",
    "Follow me on Google Giggles!!",
    "I was watchin yuyushiki and im confused where the computer club relates",
    "Wowaka, Weezer, More similar than you think.",
    "nothing really mattress who chairs",
    "Two Four Six Eight <br />You've been staying up too late",
    "These players come to get me 'cause they'd like my behind",
    "Kekeke no Kinou Ke no Kinouu~",
    "Property of Turn 10 Studios Do not copy or redistribute All rights reserved",
    "Hurting for a Very Hurtful Pain",
    "eye am not a cow",
    "Reimu in 3... 2... 1...",
    "Versitle",
    "Vote for the Instant-Karma-Party right now!",
    "Wa-oh, Wa-oh, a mirra on da wall, Believen in myselfff~",
    "IM A SUPER CUTIE BELIEVAAAA~",
    "Rina got 6 mil views on youtube go give her congrats fo that",
    "Touhou when she starts a project on Final Cut Pro IDK I just like the fumos",
    "Sends other UNIX boxes to /dev/null.",
    "LAID ON JOKE!!!!",
    "I SAY I SAY MY HEAVEEEEN~",
    "i do feel bad for yuki after watching the haruhi movie..",
    "Hibikase playing while going 200mph feels based AF",
    "sometimes people speak and you know what i just dont listen",
    "Ya never say hey, or remember my name, and its probably cause, you think you're cooler than me..",
    "Drive thru, raw as hell.",
    "haters gonna hate",
    "hataters gonna hatate",
    "my haters are just jealous they don't have even a fraction of my swag.",
    "Separate art from the artist.",
    "Separate sites from the citer.",
    "Me, studying, and manual labor don't mix.",
    "shi be bussin",
    "la-la-lova-ka!",
    "boop boop boop boop boop boop boop boop boop boop boop boop boop boop boop",
    "FIVE OF A KIND!",
    "Feel free to visit Windo 7.6!",
    "flatpancakesss? yea, your website design is flat compared to THIS!!",
    "liqui and cak wish they had even 1% of my talent..",
    "Happy Tokomaru Friday!",
    "i still seeU andria..",
    "no driver support?",
    "Emmylove and Key2050!",
    "Waddl doo",
    "I spilled coke all over my Girls und Panzer artbook...",
    "If you ask people to help with stuff like this, they don't help. 98% of this is written by me.",
    "Yachatta.",
    "If you refresh, there's a chance you might get this twice. True randomness leads to stuff like that, but it makes it feel fake doesn't it?",
    "Self confidence is important.",
    "It seems such a waste of time, if that's what it's all about",
    "In this cruel play, I'll leave the rest to you, okay?",
    "In this cruel play, leave it to Yotsuya-san, okay?",
    "Intro-like...something or other.",
    "Allow me to introduce you to my CL Mercedes.",
    "Got a ride thats smoother than a limousine",
    "Bocchi-chan, cola!",
    "idk if otacon should be saying that in mgs2",
    "Collecting money from CDs is Potato Pro Ltd.'s potato business model",
    "Under the great name of Hakurei-Chang!",
    "Just cuz the sites blue doesn't make me a communist",
    "Yodel kid, you changed...",
    "capitalization is overrated thats pretty capitalist",
    "Capitalization Is Underrated That Gets Me A Nice Capri",
    "im kidding guys. /j or whatever da kids kid about",
    "this site has been made by over 3 unique powerbook g4's. got damn.",
    "Cirno's Advanced Math Class",
    "hello i am albania crash gif due to poor technology in my country i am not able to crash your browser. please be so kind and press Ctrl + R (or Command + R) to crash this site. thank you.",
    "Yall ever seen Re: Cutie Honey?",
    "Maybe instead of ragebaiting you can spend your time friendmaxxing and smilebaiting :)",
    "All warfare is based on Missile Systems - Sun Tzu",
    "It takes 3min to Listen to a 3min Song",
    "We are bound by our mutual superiority complex, and always at disagreement.",
    "Go Woke Go Broke",
    "This site loads on a 3DS",
    "This site loads on a iPhone 2G, lucky-ch doesn't!",
    "This site loads on a PowerBook 165c, but they can't see this text because JS support is iffy..",
    "I miss neptunia.",
    "Nep",
    "Spring of Dreams, it's in my memories.",
    "Voice from endless night, is callin to me so sadly, wow...",
    "My sorrow, already, has melted.. however. <br />Your words, too. Have melted, but...",
    "IF I was smarter, id average multiple random results to get true randomness. not that I will.",
    "I recommend DSP1 Windows 7! It's easy, comfortable to use, and fast!",
    "I recommend Mac OS 8! It's the worlds FIRST internet-ready OS!",
    "I recommend Mac OS X Snow Leopard! The world's most advanced operating system, finely tuned.",
    "PowerComputing is FIGHTING BACK FOR THE MAC!",
    "Tick Tack, Tick Tack",
    "YOU WONT LAST 10 SECONDS OVER THE COUNTY LINE!",
    "when you feel upset just throw your bocchi against the wall grrr",
    "Blue Regrets, Blue Tears",
    "When can we get a g5 in our PowerBooks?",
    "Pippih-P!",
    "Biggest Meanies Ever.",
    "YOUR MOMMY DOESNT LIKE YOU!",
    "#gradytwtselfieday",
    "ex /jp/ takes admin no i aint jokin",
    "i want to sniff grady",
    "good morning grady from gradystudios on twitter dot cum",
    "I want doremy to lick me",
    "PoorGrady",
    "Just sell it on, if your soft doesn't bring you joy then let it do so for someone else. becoming popular was a travesty.",
    "Reimu Costco",
    "This site requires a WindyFall gold account.",
    "We love you Boris <br />Your CAA Family",
    "Touhou 17.5 Dolphin Folder",
    "Suika F1 wine incident",
    "You're an idiot :)",
    "At least I'm not Sara parasocially putting buttons for friends I don't have B)",
    "the missile knows where it is",
    "What if. You wanted summer to end. But Haruhi said: What if. You wanted summer to end. But Haruhi said: What if. You wanted summer to end. But Haruhi said: What if. You wanted summer to end. But Haruhi said: What if. You wanted summer to end. But Haruhi said: What if. You wanted summer to end. But Haruhi said: What if. You wanted summer to end. But Haruhi said: What if. You wanted summer to end. But Haruhi said:",
    "NICO NICO PUNCH!!! Back, Down, Forward, Tap A Repeatedly.",
    "Sunny Day Song, Sunny Day Song",
    "Keiichi-kun's been feeling down lately. Maybe he's in a bad mood. <br />I wonder, maybe he's on his period?",
    "Electrical system failure. <br />Go to dealer",
    "NOW THAT'S WHAT I CALL MUSIC",
    "Be Gay, Do Crime.",
    "Yakupuri!",
    "I come from a land down under",
    "Every apple, eventually goes bad.",
    "EXPLOSION!",
    "Three letter agent glow so bright",
    "So now if I want the Ferrari and the Mercedes I have to buy copies of the game or wait a year until they become DLC. Fucking GAY",
    "You see, in this world, there's two kinds of people, my friend. Those with loaded guns, and those who dig. You dig.",
    "JohnnyGadget - ROBLOX LIFE",
    "the next small, and big things from apple.",
    "Guten Morgen!",
    "But they have the sex - Steve Jobs",
    "Your computer might be at risk.",
    "Don't believe everything you see on the internet.",
    "Believe everything you see on the internet!",
    "That's how long it takes to load on my commodore 64!",
    "i blame miyoi for my mac not working",
    "nesoberi girl overdose",
    "i want to sniff grady",
    "The ultimate open-door policy",
    "Me and PowerComputing have something in common, we lost our license for speeding.",
    "KILL ME BABY!!",
    "Bad Apple Bottom Jeans?",
    "YAWATA YAWATA BAKETEMO WAKEMITAMA!!!",
    "Also visit senseal.github.io!",
    "Fumo Fumo ᗜˬᗜ",
    "Also visit theuselessweb.com!",
    "dudes be like subway sucks",
    "she sells sea shells on the sea shore",
    "Monopoly Mermaid Monday",
    "when i wanna see green spikes in activity monitor, i press Command + R on this page.",
    "With MMX Technology!",
    "Delta Free Wifi hate zone",
    "i thought about writing more lowercase phrases, but im out of ideas.",
    "Charging is not supported with this accessory.",
    "Equal Opportunity Hater I don't care about your background",
    "Equal Opportunity Employer I'm hiring somebody to write these slogans",
   "Marisa stole my precious website<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />",
    "Unplug the accessory using too much power to re-enable USB devices.",
    "Please write forged signature here:",
    "IE5 4 Mac compatible!",
    "i got like thousands of dollars in roblox items wth do i do with those",
    "does this formatting thing even work?",
    "does this formatting thing <br />even work?",
    "You're chasing a ghost with no brakes, SLOW DOWN!",
    "While my neighbor's at super speed, I started my honeycomb day off.",
    "Even though I like baths, they're coming at me to k177 (T T)",
    "I like baths, So I log into my bathing profile.",
    "THIS KILLS THE PATCHE",
    "super speed car society car meet. macdonal. hungy jak. car park nex 2 police statio",
    "your go made grammar error in 2 hour",
    "Ok the enclave have sick power armor you gotta admit.",
    "windoe",
    "But, can you really fly if you work hard? <br />I'm making a face that looks like that.",
    "Anata to watashi, kago no naka. Anata mo watashi, chikuhaku.",
    "Cause we don't wanna hear that weak shit no mo",
    "Rock Stars are supposed to be a bit dodgy! - Eliza",
    "i'm not dropping some 60's on a fumo im sorry",
    "And the name Haruhi Suzumiya... It doesn't matter what... Don't you remember it?",
    "It's two hundred million five thousand six hundred years too soon for this!",
    "Z dot... what?",
    "Akariiiiiiiii~n!"
);
